Update proto types to match specification
sideprotocol/ibcswap pull request #21
Opened 2023-03-27 20:19 UTC by EmilGeorgiev

2023-03-31 01:01 UTC, liangping requested changes
It's much better.  Few suggestion to be improved

2023-03-31 01:01 UTC, liangping commented on modules/apps/100-atomic-swap/keeper/msg_server_make_swap.go
> +	if balance.Amount.BigInt().Cmp(msg.SellToken.Amount.BigInt()) < 0 {
Amount has `Gt()` an `Lt()` functions. Would be better to change

2023-03-31 01:01 UTC, liangping commented on modules/apps/100-atomic-swap/keeper/msg_server_take_swap.go
> +// TakeSwap is the step 5 (Lock Order & Lock Token) of the atomic swap: https://github.com/liangping/ibc/blob/atomic-swap/spec/app/ics-100-atomic-swap/ibcswap.png
Would be better to use URL of cosmos repo. Https://github.com/cosmos/ibc

2023-03-31 01:01 UTC, liangping commented on modules/apps/100-atomic-swap/keeper/msg_server_take_swap.go
> +	// Checks if the order has already been taken
I am thinking to add a new LOCK status for order. And also add status changing here.

2023-03-31 01:01 UTC, liangping commented on modules/apps/100-atomic-swap/keeper/msg_server_take_swap.go
> +	if balance.Amount.BigInt().Cmp(msg.SellToken.Amount.BigInt()) < 0 {
The same issue

2023-03-31 01:01 UTC, liangping commented on proto/ibc/applications/atomic_swap/v1/tx.proto
> +  rpc MakeSwap(MakeSwapMsg) returns (MsgMakeSwapResponse);
Seems that Use prefix Msg is more common than suffix in cosmos. 

I know that's the problem of spec.

2023-04-01 08:12 UTC, EmilGeorgiev commented on modules/apps/100-atomic-swap/keeper/msg_server_take_swap.go
> +	// Checks if the order has already been taken
I can make this in separate PR, this is already too big

2023-04-01 08:15 UTC, EmilGeorgiev commented on modules/apps/100-atomic-swap/keeper/msg_server_make_swap.go
> +	if balance.Amount.BigInt().Cmp(msg.SellToken.Amount.BigInt()) < 0 {
Done

2023-04-01 08:15 UTC, EmilGeorgiev commented on modules/apps/100-atomic-swap/keeper/msg_server_take_swap.go
> +// TakeSwap is the step 5 (Lock Order & Lock Token) of the atomic swap: https://github.com/liangping/ibc/blob/atomic-swap/spec/app/ics-100-atomic-swap/ibcswap.png
Done

2023-04-01 08:15 UTC, EmilGeorgiev commented on modules/apps/100-atomic-swap/keeper/msg_server_take_swap.go
> +	if balance.Amount.BigInt().Cmp(msg.SellToken.Amount.BigInt()) < 0 {
Done

2023-04-01 08:16 UTC, EmilGeorgiev commented on proto/ibc/applications/atomic_swap/v1/tx.proto
> +  rpc MakeSwap(MakeSwapMsg) returns (MsgMakeSwapResponse);
Can I make this in a separate issue and separate PR? I also can update the specification

2023-04-01 09:17 UTC, liangping commented on proto/ibc/applications/atomic_swap/v1/tx.proto
> +  rpc MakeSwap(MakeSwapMsg) returns (MsgMakeSwapResponse);
Yeah. That would be better.

2023-04-10 14:26 UTC, merged